let typeColors = {
  grass: "bg_green",
  poison: "bg_lightGreen",
  flying: "bg_gray",
  fire: "bg_red",
  electric: "bg_yellow",
  ground: "bg_brown",
  normal: "bg_beige",
  water: "bg_blue",
  bug: "bg_lime",
  fairy: "bg_pink",
  fighting: "bg_orange",
  psychic: "bg_purple",
  rock: "bg_ligthGray",
  steel: "bg_silver",
  ice: "bg_lightBlue",
  ghost: "bg_lightPurple",
  dragon: "bg_silverGray",
};
